notifications:
  email: false
language: node_js

node_js:
- '9'
- '8'
- '7'

cache:
  directories:
  - $(pwd)/node_modules

script:
  - npm run build

deploy:
  - provider: npm
    email: guillaume.lunik@gmail.com
    on:
      tags: true
    api_key:
      secure: E8ObX88JQ344txH+b1d1PVIBMUY/Y7tFZmUi0UQ0EsvRRk2VXbmI3rRM6DFM1dnTceMNNcMmAw+tLxz7QwEFocNn+jhDSSIvA6eO6i2YFt/Mnv7ehPhVv0qSzgJFySLhnkzzuL76UcH6GY8ka4v9cTAbyLLcBbCd5W0K8uEMi5ugwWh7uBToWGO/gp+ob1DtU/mOtcH8xBrpWyxxcqW1Wx+23nNQxsbVOsKN80lagTXkqzAs9soaTcf6Id+y7Z6QRs4LECRsM5yKEZVwPTK+yVXJ7rtcOaXCxSW5OvFdW9BTYNKfzodujfTjwnecGoiDueruypNCjFExdx1l9Fi6mm+jcqC2SeNFUfKeMfCvbI1qTfHrnffEb/2EOrOEA6glJ89eELTT/lc5H5fZYD0fsXN5kj9u82HOdfGpAeiAXUJUYvU4sqnmmzukgp+cIGjOxyCowGvqg9pkRscls3l6vWF0hZL/zDrMAzoZWwrfykYrkbGud+eU1xnjxSd0UJzPpXClyR6sZSRYQskNeBvx0dERIGhoaPOyt08hdDRjXPHDozbjqcFKxsYBhEggjq+ugOKVv1Qpzk/aqTTwM4JYE3JyTEoeaYpCcVKyi6oRQ85HkWZVrKdiqebWImo3/Uiur+kmk1J4SmZQZnauskQuVBl37R7+nN/+B6V+5LJEBQQ=
