notifications:
  email: false
language: node_js

node_js:
- '9'
- '8'
- '7'

cache:
  directories:
  - $(pwd)/node_modules

script:
  - npm run build

deploy:
  - provider: npm
    email: guillaume.lunik@gmail.com
    on:
      tags: true
    api_key:
      secure: GBIozR0eDh7GACQ2ijOZhHfHpQx/WbRnTlDIvwOUxavrTk/ek5NqV8M3KTv+NxuxylFQq6HvAu96yAnZisXAvR2Btvy3PLuow6A4qbodPrajwrCAca3ZaKxluQ65cihri9yZroECXPPMRCDsMRVUjpF+wXP4MMxrzcsPX9jt4VQfaz4YRmqVFzndGd6zWKZ/WgHZAyjWwNlQz2xA15hnyUgkeeWYZAmJV085K2JzuU1Ucr14ITcFdXEShZXccWGtiygH9rEcTaVGk8wPyYSmUL8R0VBQN5LWEqFyxONWfimJjtp6QJa3p/Uv9ODgDDiDtcSuyG0zHOb48HfIvoEXf8uauNVXHppc0JkjYiLvvKO6h2oW8ll46E5PfTRCBvjr3IAM2lnok9yPtFaLniBCsQuGj7ac2cAUCQMu4bEowk5Mbrt8yT6WWaBuYetSvspCTj5F1LdcP4TJMPebJpvfyiHhlcU2eKi/0cSfT/7CHlbpnybb3MrXn2BjMVYSrR4yBTeMn5b7bmyejgtZvYNGipDyoab5WFLd5gmgLy/EjVZrwJSX4vtSP6tZE+AkJjhn6RSQpQX7NAsW+4HzLyj0JdJWkrGJkp0JNRx/jwIdYDtosnzXH2DxfQ4Wv22Kd+uKW5h8Cytu6ViCir/2QniqcfAE5NleCtL5GNSvRliLyDU=